In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
import numpy as np

In [ ]:
a = np.array([9,10,11,12])
b = np.array([5,6,7,8])

In [ ]:
a[0], a[1]

(9, 10)

In [ ]:
a[:0]

array([], dtype=int64)

In [ ]:
a[0:]

array([ 9, 10, 11, 12])

In [ ]:
a[1:]

array([10, 11, 12])

In [ ]:
a[1:3]

array([10, 11])

In [ ]:
b[[0,2,-1]]

array([5, 7, 8])

In [ ]:
a

array([ 9, 10, 11, 12])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
c = np.array([3.1, 3.2, 3.3, 3.4])

In [ ]:
c

array([3.1, 3.2, 3.3, 3.4])

In [ ]:
c.dtype

dtype('float64')

# ***Dimesnion and shapes***

In [ ]:
A=np.array([
  [1,2,3,4],
  [4,5,6,7]          
])

In [ ]:
A.shape

(2, 4)

In [ ]:
A.ndim

2

In [ ]:
A.size

8

In [ ]:
D=np.array([[[
      [8,9,10,11],
      [12,13,14,15],
    ],
    [
      [16,17,18],
      [19,20,21,22]
    ]
]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [ ]:
D.ndim

3

In [ ]:
D.size

4

In [ ]:
D.shape

(1, 2, 2)

## **Indexing and slicing of Matrices**

In [ ]:
A=np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]    
])

In [ ]:
A.ndim

2

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[2:,1:2]

array([[8]])

In [ ]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:,1:2]

array([[2],
       [5],
       [8]])

In [ ]:
A[1:2]

array([[4, 5, 6]])

In [ ]:
A[:2,2:]

array([[3],
       [6]])

In [ ]:
A[1]= np.array([10,10,10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A.sum()

60

In [ ]:
A.mean()

6.666666666666667

In [ ]:
A.std()

3.464101615137755

In [ ]:
A.var()

12.000000000000002

In [ ]:
A.sum(axis=0)

array([18, 20, 22])

# **Broadcasting And Vectorized Operations**

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a*10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a +=100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
l = [0,1,3,4]
[i * 2 for i in l]

[0, 2, 6, 8]

In [ ]:
b = np.array([10,11,12,13 ])

In [ ]:
a+b

array([110, 112, 114, 116])

In [ ]:
a=b

# Boolean **Arrays**

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a[0],a[-1]

(0, 4)

In [ ]:
a[[True, True, False, False, True]]

array([0, 1, 4])

In [ ]:
a >=2

array([False, False,  True,  True,  True])

In [ ]:
a[a>=2]

array([2, 3, 4])

In [ ]:
a.mean()

2.0

In [ ]:
a[a>a.mean()]

array([3, 4])

In [ ]:
a[~(a > a.mean())]

array([0, 1, 2])

In [ ]:
a[(a==0) | (a==1)]

array([0, 1])

In [ ]:
a[(a<=2) & (a%2==0)]

array([0, 2])

In [ ]:
A = np.random.randint(200, size=(3,3))

In [ ]:
A

array([[101,  71,  90],
       [ 56, 151,  60],
       [ 64, 177,  52]])

In [ ]:
A[np.array([
[True, False, True],
            [True, True, False],
            [False, True, False]
            ])]

array([101,  90,  56, 151, 177])

In [ ]:
a[a>50]

array([], dtype=int64)

# **Linear Algebra**

In [ ]:
import numpy as np

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B = np.array([
              [11,12,13],
              [14,15,17],
              [18,19,20]
])

In [ ]:
#DotProduct
A.dot(B)

array([[ 93,  99, 107],
       [222, 237, 257],
       [351, 375, 407]])

In [ ]:
#CrossProduct
A@B

array([[ 93,  99, 107],
       [222, 237, 257],
       [351, 375, 407]])

In [ ]:
B.T

array([[11, 14, 18],
       [12, 15, 19],
       [13, 17, 20]])

In [ ]:
B.T @A

array([[193, 236, 279],
       [205, 251, 297],
       [221, 271, 321]])

# **Size Of Object In Memory**

In [ ]:
#sys.getsizeof(1)
#sys.getsizeof(10*100)

In [ ]:
np.dtype(int).itemsize

8

In [ ]:
np.dtype(float).itemsize

8

# **Performance**

In [ ]:
l =list(range(1000000))

In [ ]:
a = np.arange(10000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 602 µs, sys: 74 µs, total: 676 µs
Wall time: 512 µs


333283335000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 285 ms, sys: 35.9 ms, total: 321 ms
Wall time: 324 ms


333332833333500000

# **Useful Numpy Function**

In [ ]:
np.random.random(size = 2)

array([0.53020455, 0.63592707])

In [ ]:
np.random.normal(size = 3)

array([-0.60012646, -0.09288124, -1.01846533])

In [ ]:
np.random.rand(5,7)

array([[0.76399626, 0.29457586, 0.91197364, 0.69074806, 0.67578599,
        0.66651779, 0.18843553],
       [0.64899138, 0.91580174, 0.60990127, 0.67443293, 0.07017084,
        0.3222559 , 0.21268603],
       [0.12574383, 0.1250163 , 0.21329273, 0.80756209, 0.77813171,
        0.04380486, 0.68256761],
       [0.68634706, 0.53673121, 0.03734716, 0.67458986, 0.71422057,
        0.3020135 , 0.12760282],
       [0.00785729, 0.09219793, 0.28651868, 0.77788359, 0.70142923,
        0.35696047, 0.93707283]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,3)

array([], dtype=int64)

In [ ]:
np.arange(1,4,-7)

array([], dtype=int64)

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.linspace(0,2,7)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [ ]:
np.linspace(8,1,20, False)

array([8.  , 7.65, 7.3 , 6.95, 6.6 , 6.25, 5.9 , 5.55, 5.2 , 4.85, 4.5 ,
       4.15, 3.8 , 3.45, 3.1 , 2.75, 2.4 , 2.05, 1.7 , 1.35])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4, k=5)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])